
do->
	eventToIE =
		CheckboxStateChange: "CheckboxStateChange"
		DOMActivate: "DOMActivate"
		DOMAttrModified: "DOMAttrModified"
		DOMCharacterDataModified: "DOMCharacterDataModified"
		DOMNodeInserted: "DOMNodeInserted"
		DOMNodeInsertedIntoDocument: "DOMNodeInsertedIntoDocument"
		DOMMenuItemActive: "DOMMenuItemActive"
		DOMMenuItemInactive: "DOMMenuItemInactive"
		DOMNodeRemoved: "DOMNodeRemoved"
		DOMNodeRemovedFromDocument: "DOMNodeRemovedFromDocument"
		DOMMouseScroll: "DOMMouseScroll"
		DOMSubtreeModified: "DOMSubtreeModified"
		RadioStateChange: "RadioStateChange"
		abort: "onabort"
		afterprint: "onafterprint"
		afterupdate: "onafterupdate"
		beforeupdate: "onbeforeupdate"
		beforecut: "onbeforecut"
		beforecopy: "onbeforecopy"
		beforepaste: "onbeforepaste"
		beforeunload: "onbeforeunload"
		beforeeditfocus: "onbeforeeditfocus"
		beforeprint: "onbeforeprint"
		blur: "onblur"
		bounce: "onbounce"
		broadcast: "onbroadcast"
		click: "onclick"
		cellchange: "oncellchange"
		cut: "oncut"
		copy: "oncopy"
		change: "onchange"
		commandupdate: "oncommandupdate"
		close: "onclose"
		command: "oncommand"
		contextmenu: "oncontextmenu"
		dblclick: "ondblclick"
		dragstart: "ondragstart"
		drag: "ondrag"
		dragenter: "ondragenter"
		dragleave: "ondragleave"
		dragover: "ondragover"
		drop: "ondrop"
		dragend: "ondragend"
		dataavailable: "ondataavailable"
		datasetchanged: "ondatasetchanged"
		datasetcomplete: "ondatasetcomplete"
		dragdrop: "ondragdrop"
		dragexit: "ondragexit"
		draggesture: "ondraggesture"
		errorupdate: "onerrorupdate"
		error: "onerror"
		focus: "onfocus"
		focusin: "onfocusin"
		focusout: "onfocusout"
		finish: "onfinish"
		filterchange: "onfilterchange"
		gotpointercapture: "ongotpointercapture"
		help: "onhelp"
		input: "oninput"
		keydown: "onkeydown"
		keypress: "onkeypress"
		keyup: "onkeyup"
		load: "onload"
		lostpointercapture: "onlostpointercapture"
		losecapture: "onlosecapture"
		mousedown: "onmousedown"
		mouseup: "onmouseup"
		mouseover: "onmouseover"
		mousemove: "onmousemove"
		mouseout: "onmouseout"
		overflow: "onoverflow"
		overflowchanged: "onoverflowchanged"
		pointerdown: "onpointerdown"
		pointerup: "onpointerup"
		pointercancel: "onpointercancel"
		pointermove: "onpointermove"
		pointerover: "onpointerover"
		pointerout: "onpointerout"
		pointerenter: "onpointerenter"
		pointerleave: "onpointerleave"
		paste: "onpaste"
		popuphidden: "onpopuphidden"
		popuphiding: "onpopuphiding"
		popupshowing: "onpopupshowing"
		popupshown: "onpopupshown"
		propertychange: "onpropertychange"
		resize: "onresize"
		reset: "onreset"
		rowenter: "onrowenter"
		rowexit: "onrowexit"
		rowsdelete: "onrowsdelete"
		rowinserted: "onrowinserted"
		readystatechange: "onreadystatechange"
		scroll: "onscroll"
		start: "onstart"
		selectstart: "onselectstart"
		stop: "onstop"
		select: "onselect"
		submit: "onsubmit"
		touchstart: "ontouchstart"
		touchend: "ontouchend"
		touchmove: "ontouchmove"
		touchenter: "ontouchenter"
		touchleave: "ontouchleave"
		touchcancel: "ontouchcancel"
		underflow: "onunderflow"
		unload: "onunload"

	$X.Class::addListener = (event, callback)->
		for item in @
			try
				if typeof item.addEventListener == 'function'
					item.addEventListener event, callback, false
				else item.attachEvent eventToIE[event], callback, false
		@
	$X.Class::removeListener = (event, callback)->
		for item in @
			try
				if typeof item.removeEventListener == 'function'
					item.removeEventListener event, callback, false
				else item.detachEvent eventToIE[event], callback, false
		@
